
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.net.InetAddress;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.Multipart;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Abhijit
 */

public class SendFram extends javax.swing.JFrame {

    /**
     * Creates new form SendFram
     */
    String password;
    String mail="";
    File f;
    public SendFram() {
        initComponents();
        
        try
        {
            FileReader f=new FileReader("id.txt");
            int val=0;
            while((val=f.read())!=-1)
            {
                mail=mail+(char)val;
            }
            mail=mail.trim();
            
            String str[]=mail.split("/");
            tf1.setText(str[0].trim());
            password=str[1];
            password=password.trim();
            
        }
        catch(Exception e)
        {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tf5 = new java.awt.TextArea();
        tf3 = new javax.swing.JTextField();
        tf1 = new javax.swing.JTextField();
        tf2 = new javax.swing.JTextField();
        tf4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        at = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1086, 653));
        setUndecorated(true);
        getContentPane().setLayout(null);

        tf5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        getContentPane().add(tf5);
        tf5.setBounds(200, 270, 690, 380);

        tf3.setBorder(null);
        getContentPane().add(tf3);
        tf3.setBounds(270, 170, 430, 30);

        tf1.setBorder(null);
        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });
        getContentPane().add(tf1);
        tf1.setBounds(260, 70, 540, 30);

        tf2.setBorder(null);
        getContentPane().add(tf2);
        tf2.setBounds(270, 120, 400, 30);

        tf4.setBorder(null);
        getContentPane().add(tf4);
        tf4.setBounds(270, 220, 120, 30);

        jButton1.setForeground(new java.awt.Color(217, 67, 53));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/attac.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(980, 0, 50, 50);

        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/send.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1030, 0, 40, 50);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrow-16.png"))); // NOI18N
        jButton3.setText("Logout                                                                Compose");
        jButton3.setBorder(null);
        jButton3.setContentAreaFilled(false);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(0, 0, 570, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Attachment");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(470, 210, 90, 40);

        at.setEnabled(false);
        getContentPane().add(at);
        at.setBounds(560, 210, 340, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrow-16.png"))); // NOI18N
        jLabel3.setText("Sent Mail");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(840, 0, 130, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/compose.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -20, 1090, 690);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        dispose();
        
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      //JFileChooser chooser=new JFileChooser();
      //chooser.showOpenDialog(null);
      //File f=chooser.getSelectedFile();
      //String filename=f.getAbsolutePath();
   
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        try
        {
            
               Properties props = new Properties();
		props.put("mail.smtp.host", "smtp.gmail.com");
		props.put("mail.smtp.socketFactory.port", "465");
		props.put("mail.smtp.socketFactory.class","javax.net.ssl.SSLSocketFactory");
		props.put("mail.smtp.auth", "true");
		props.put("mail.smtp.port", "465");

		Session session = Session.getInstance(props,
			new javax.mail.Authenticator() {
				protected PasswordAuthentication getPasswordAuthentication() {
					return new PasswordAuthentication(tf1.getText(),password);
				}
			});
                Message message = new MimeMessage(session);
                message.setFrom(new InternetAddress("from@no-spam.com"));
                message.setRecipients(Message.RecipientType.TO,
					InternetAddress.parse(tf2.getText()));
                 
			message.setSubject(tf4.getText());
			message.setText(tf5.getText());

			Transport.send(message);
                        int check=0;
                        String msg=tf5.getText();
                        String data[]=msg.split("\n");
                        Class.forName("oracle.jdbc.driver.OracleDriver");
                        Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","oracle");
                        PreparedStatement ps=con.prepareStatement("select * from words");
                        ResultSet rs=ps.executeQuery();
                        while(rs.next())
                        {
                              for(int i=0;i<data.length;i++)
                            {
                                String msges[]=data[i].split(" ");

                                for(int j=0;j<msges.length;j++)
                                {

                                    if(rs.getString(1).equalsIgnoreCase(msges[j]))
                                    {
                                       check=1;
                                       break;
                                    }
                                }
                            }
                        }
                        
                        Date d=new Date();

                        int day=d.getDate();
                        int month=1+d.getMonth();
                        int year=1900+d.getYear();
                        
                        
                        if(at.getText().equals(""))
                        {
                            Message message1 = new MimeMessage(session);
                            message1.setFrom(new InternetAddress("from@no-spam.com"));
                            message1.setRecipients(Message.RecipientType.TO,InternetAddress.parse("sood232@gmail.com"));
                            message1.setSubject(tf4.getText());
                            message1.setText(tf5.getText());
                        }
                        else
                        {
                            // Attachement
                                Multipart multipart = new MimeMultipart();
                                MimeBodyPart attachPart = new MimeBodyPart();
                                attachPart.attachFile(at.getText());
                                multipart.addBodyPart(attachPart);
                                message.setContent(multipart);
                        }
                        
                      
			Transport.send(message);
                        String date=day+"/"+month+"/"+year;
                        
                        PreparedStatement ps2=con.prepareStatement("insert into sent values (?,?,?)");
                        ps2.setString(1,tf2.getText());
                        ps2.setString(2,date);
                        ps2.setString(3,tf5.getText());
                        ps2.executeUpdate();
                        
                                

                        
                        String ip=InetAddress.getLocalHost().toString();
                        if(check==1)
                        {
                            PreparedStatement ps1=con.prepareStatement("insert into smail values(?,?,?,?,?)");
                            ps1.setString(1,tf1.getText());
                            ps1.setString(2,tf2.getText());
                            ps1.setString(3,ip);
                            ps1.setString(4,tf5.getText());
                            ps1.setString(5,date);
                            ps1.executeUpdate();
                        }
        
                        JOptionPane.showMessageDialog(this,"Mail Sent Sucessfully");
                      
                      tf2.setText("");
                      tf3.setText("");
                      tf4.setText("");
                      tf5.setText("");
                                                             
        }
        catch(Exception e)
        {
               System.out.println(e);
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        JFileChooser fc=new JFileChooser();
        int i=fc.showOpenDialog(this);
        if(i==JFileChooser.APPROVE_OPTION)
        {
            f=fc.getSelectedFile();
            at.setText(f.getPath());
        }
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        SentMail m=new SentMail();
        m.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SendFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SendFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SendFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SendFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SendFram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField at;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf4;
    private java.awt.TextArea tf5;
    // End of variables declaration//GEN-END:variables
}
